/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbrirOsRouteImport } from './routes/abrir-os'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as AreaDeAtendimentoCuritibaRouteImport } from './routes/area-de-atendimento-curitiba'
import { Route as AreasAtendidasRouteImport } from './routes/areas-atendidas'
import { Route as AssistenciaTecnicaRouteImport } from './routes/assistencia-tecnica'
import { Route as AssistenciaTecnicaCuritibaRouteImport } from './routes/assistencia-tecnica-curitiba'
import { Route as AssistenciaTecnicaEmpresasCuritibaRouteImport } from './routes/assistencia-tecnica-empresas-curitiba'
import { Route as AtendimentoUrgenteRouteImport } from './routes/atendimento-urgente'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as AvaliarRouteImport } from './routes/avaliar'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as ChecklistPublicacaoRouteImport } from './routes/checklist-publicacao'
import { Route as ChecklistsDeReparoRouteImport } from './routes/checklists-de-reparo'
import { Route as ComoAvaliarRouteImport } from './routes/como-avaliar'
import { Route as ComoEscolherTecnicoPrecoPrazoRouteImport } from './routes/como-escolher-tecnico-preco-prazo'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ConsertoDeNotebookCuritibaRouteImport } from './routes/conserto-de-notebook-curitiba'
import { Route as ConsultarOsRouteImport } from './routes/consultar-os'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CreditosDeImagensRouteImport } from './routes/creditos-de-imagens'
import { Route as DadosDaEmpresaRouteImport } from './routes/dados-da-empresa'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as EmpresaDeTiCuritibaRouteImport } from './routes/empresa-de-ti-curitiba'
import { Route as ExclusaoDeDadosRouteImport } from './routes/exclusao-de-dados'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FormatacaoDeComputadorCuritibaRouteImport } from './routes/formatacao-de-computador-curitiba'
import { Route as GarantiaECoberturaRouteImport } from './routes/garantia-e-cobertura'
import { Route as GestorResponsavelRouteImport } from './routes/gestor-responsavel'
import { Route as GuiaTecnicoInformaticaRouteImport } from './routes/guia-tecnico-informatica'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as OrdemDeServicoRouteImport } from './routes/ordem-de-servico'
import { Route as PatrocinadoresRouteImport } from './routes/patrocinadores'
import { Route as PoliticaDeAnunciosRouteImport } from './routes/politica-de-anuncios'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as PoliticaDePecasDoClienteRouteImport } from './routes/politica-de-pecas-do-cliente'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticaPrivacidadeRouteImport } from './routes/politica-privacidade'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PrecosEPoliticasRouteImport } from './routes/precos-e-politicas'
import { Route as ProcessoDeAtendimentoRouteImport } from './routes/processo-de-atendimento'
import { Route as PublicidadeRouteImport } from './routes/publicidade'
import { Route as RemocaoDeVirusCuritibaRouteImport } from './routes/remocao-de-virus-curitiba'
import { Route as SegurancaDosDadosRouteImport } from './routes/seguranca-dos-dados'
import { Route as SejaPatrocinadorRouteImport } from './routes/seja-patrocinador'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as StatusAnunciosRouteImport } from './routes/status-anuncios'
import { Route as StatusDaOrdemDeServicoRouteImport } from './routes/status-da-ordem-de-servico'
import { Route as StatusOsRouteImport } from './routes/status-os'
import { Route as SuporteTecnicoRemotoRouteImport } from './routes/suporte-tecnico-remoto'
import { Route as TermosOrcamentoRouteImport } from './routes/termos-orcamento'
import { Route as TermosOrcamentoPreAprovadoRouteImport } from './routes/termos-orcamento-pre-aprovado'
import { Route as TermosUsoRouteImport } from './routes/termos-uso'
import { Route as TriagemPreviewRouteImport } from './routes/triagem-preview'
import { Route as UpgradeMemoriaRamCuritibaRouteImport } from './routes/upgrade-memoria-ram-curitiba'
import { Route as UpgradeSsdCuritibaRouteImport } from './routes/upgrade-ssd-curitiba'
import { Route as AtendimentoNacionalIndexRouteImport } from './routes/atendimento-nacional.index'
import { Route as AtendimentoNacionalSlugRouteImport } from './routes/atendimento-nacional.$slug'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as GuiasComoEscolherUmaWorkstationRouteImport } from './routes/guias.como-escolher-uma-workstation'
import { Route as GuiasOrganizacaoDeTiParaPequenosEscritoriosRouteImport } from './routes/guias.organizacao-de-ti-para-pequenos-escritorios'
import { Route as OperacaoManifestoDeProvasRouteImport } from './routes/operacao.manifesto-de-provas'
import { Route as OperacaoMensagensProntasRouteImport } from './routes/operacao.mensagens-prontas'
import { Route as OperacaoPainelConversaoRouteImport } from './routes/operacao.painel-conversao'
import { Route as OperacaoPainelGoogleBusinessRouteImport } from './routes/operacao.painel-google-business'
import { Route as RegioesIndexRouteImport } from './routes/regioes.index'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as ServicosBackupParaEmpresasRouteImport } from './routes/servicos.backup-para-empresas'
import { Route as ServicosConfiguracaoWifiCuritibaRouteImport } from './routes/servicos.configuracao-wifi-curitiba'
import { Route as ServicosConsertoDeSomEAudioCuritibaRouteImport } from './routes/servicos.conserto-de-som-e-audio-curitiba'
import { Route as ServicosConsertoDeTelevisaoRouteImport } from './routes/servicos.conserto-de-televisao'
import { Route as ServicosConsertoDeTvRouteImport } from './routes/servicos.conserto-de-tv'
import { Route as ServicosConsertoTvRouteImport } from './routes/servicos.conserto-tv'
import { Route as ServicosManutencaoPreventivaEmpresasRouteImport } from './routes/servicos.manutencao-preventiva-empresas'
import { Route as ServicosRedesEWifiRouteImport } from './routes/servicos.redes-e-wifi'
import { Route as ServicosReparoSmartTvCuritibaRouteImport } from './routes/servicos.reparo-smart-tv-curitiba'
import { Route as ServicosSuporteTecnicoEmpresarialRouteImport } from './routes/servicos.suporte-tecnico-empresarial'
import { Route as ServicosTrocaDeTelaTvCuritibaRouteImport } from './routes/servicos.troca-de-tela-tv-curitiba'
import { Route as SolucoesIndexRouteImport } from './routes/solucoes.index'
import { Route as SolucoesSlugRouteImport } from './routes/solucoes.$slug'
import { Route as AtendimentoNacionalCityBairroRouteImport } from './routes/atendimento-nacional.$city.$bairro'
import { Route as BlogCategoriaSlugRouteImport } from './routes/blog.categoria.$slug'
import { Route as RegioesCityIndexRouteImport } from './routes/regioes.$city.index'
import { Route as RegioesCityNeighborhoodRouteImport } from './routes/regioes.$city.$neighborhood'
import { Route as ServicoEmCityServiceRouteImport } from './routes/servico-em.$city.$service'
import { Route as ServicosServicoCuritibaRouteImport } from './routes/servicos.$servico.curitiba'
import { Route as ServicosConfiguracaoWifiCidadeRouteImport } from './routes/servicos.configuracao-wifi.$cidade'
import { Route as ServicosPcGamerComoFuncionaRouteImport } from './routes/servicos.pc-gamer.como-funciona'
import { Route as ServicosReparoSmartTvCidadeRouteImport } from './routes/servicos.reparo-smart-tv.$cidade'
import { Route as ServicosTrocaDeTelaTvCidadeRouteImport } from './routes/servicos.troca-de-tela-tv.$cidade'
import { Route as ServicoEmNacionalCityBairroServiceRouteImport } from './routes/servico-em-nacional.$city.$bairro.$service'
import { Route as ServicosConfiguracaoWifiCuritibaBairroRouteImport } from './routes/servicos.configuracao-wifi.curitiba.$bairro'
import { Route as ServicosConfiguracaoWifiPinhaisBairroRouteImport } from './routes/servicos.configuracao-wifi.pinhais.$bairro'
import { Route as ServicosConfiguracaoWifiSaoJoseDosPinhaisBairroRouteImport } from './routes/servicos.configuracao-wifi.sao-jose-dos-pinhais.$bairro'
import { Route as ServicosReparoSmartTvCuritibaBairroRouteImport } from './routes/servicos.reparo-smart-tv.curitiba.$bairro'
import { Route as ServicosReparoSmartTvPinhaisBairroRouteImport } from './routes/servicos.reparo-smart-tv.pinhais.$bairro'
import { Route as ServicosReparoSmartTvSaoJoseDosPinhaisBairroRouteImport } from './routes/servicos.reparo-smart-tv.sao-jose-dos-pinhais.$bairro'
import { Route as ServicosTrocaDeTelaTvPinhaisBairroRouteImport } from './routes/servicos.troca-de-tela-tv.pinhais.$bairro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbrirOsRoute = AbrirOsRouteImport.update({
  id: '/abrir-os',
  path: '/abrir-os',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaDeAtendimentoCuritibaRoute =
  AreaDeAtendimentoCuritibaRouteImport.update({
    id: '/area-de-atendimento-curitiba',
    path: '/area-de-atendimento-curitiba',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasAtendidasRoute = AreasAtendidasRouteImport.update({
  id: '/areas-atendidas',
  path: '/areas-atendidas',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenciaTecnicaRoute = AssistenciaTecnicaRouteImport.update({
  id: '/assistencia-tecnica',
  path: '/assistencia-tecnica',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenciaTecnicaCuritibaRoute =
  AssistenciaTecnicaCuritibaRouteImport.update({
    id: '/assistencia-tecnica-curitiba',
    path: '/assistencia-tecnica-curitiba',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssistenciaTecnicaEmpresasCuritibaRoute =
  AssistenciaTecnicaEmpresasCuritibaRouteImport.update({
    id: '/assistencia-tecnica-empresas-curitiba',
    path: '/assistencia-tecnica-empresas-curitiba',
    getParentRoute: () => rootRouteImport,
  } as any)
const AtendimentoUrgenteRoute = AtendimentoUrgenteRouteImport.update({
  id: '/atendimento-urgente',
  path: '/atendimento-urgente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliarRoute = AvaliarRouteImport.update({
  id: '/avaliar',
  path: '/avaliar',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistPublicacaoRoute = ChecklistPublicacaoRouteImport.update({
  id: '/checklist-publicacao',
  path: '/checklist-publicacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsDeReparoRoute = ChecklistsDeReparoRouteImport.update({
  id: '/checklists-de-reparo',
  path: '/checklists-de-reparo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoAvaliarRoute = ComoAvaliarRouteImport.update({
  id: '/como-avaliar',
  path: '/como-avaliar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoEscolherTecnicoPrecoPrazoRoute =
  ComoEscolherTecnicoPrecoPrazoRouteImport.update({
    id: '/como-escolher-tecnico-preco-prazo',
    path: '/como-escolher-tecnico-preco-prazo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsertoDeNotebookCuritibaRoute =
  ConsertoDeNotebookCuritibaRouteImport.update({
    id: '/conserto-de-notebook-curitiba',
    path: '/conserto-de-notebook-curitiba',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsultarOsRoute = ConsultarOsRouteImport.update({
  id: '/consultar-os',
  path: '/consultar-os',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosDeImagensRoute = CreditosDeImagensRouteImport.update({
  id: '/creditos-de-imagens',
  path: '/creditos-de-imagens',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosDaEmpresaRoute = DadosDaEmpresaRouteImport.update({
  id: '/dados-da-empresa',
  path: '/dados-da-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaDeTiCuritibaRoute = EmpresaDeTiCuritibaRouteImport.update({
  id: '/empresa-de-ti-curitiba',
  path: '/empresa-de-ti-curitiba',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusaoDeDadosRoute = ExclusaoDeDadosRouteImport.update({
  id: '/exclusao-de-dados',
  path: '/exclusao-de-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatacaoDeComputadorCuritibaRoute =
  FormatacaoDeComputadorCuritibaRouteImport.update({
    id: '/formatacao-de-computador-curitiba',
    path: '/formatacao-de-computador-curitiba',
    getParentRoute: () => rootRouteImport,
  } as any)
const GarantiaECoberturaRoute = GarantiaECoberturaRouteImport.update({
  id: '/garantia-e-cobertura',
  path: '/garantia-e-cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorResponsavelRoute = GestorResponsavelRouteImport.update({
  id: '/gestor-responsavel',
  path: '/gestor-responsavel',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaTecnicoInformaticaRoute = GuiaTecnicoInformaticaRouteImport.update({
  id: '/guia-tecnico-informatica',
  path: '/guia-tecnico-informatica',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdemDeServicoRoute = OrdemDeServicoRouteImport.update({
  id: '/ordem-de-servico',
  path: '/ordem-de-servico',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadoresRoute = PatrocinadoresRouteImport.update({
  id: '/patrocinadores',
  path: '/patrocinadores',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeAnunciosRoute = PoliticaDeAnunciosRouteImport.update({
  id: '/politica-de-anuncios',
  path: '/politica-de-anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePecasDoClienteRoute =
  PoliticaDePecasDoClienteRouteImport.update({
    id: '/politica-de-pecas-do-cliente',
    path: '/politica-de-pecas-do-cliente',
    getParentRoute: () => rootRouteImport,
  } as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadeRoute = PoliticaPrivacidadeRouteImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosEPoliticasRoute = PrecosEPoliticasRouteImport.update({
  id: '/precos-e-politicas',
  path: '/precos-e-politicas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessoDeAtendimentoRoute = ProcessoDeAtendimentoRouteImport.update({
  id: '/processo-de-atendimento',
  path: '/processo-de-atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicidadeRoute = PublicidadeRouteImport.update({
  id: '/publicidade',
  path: '/publicidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RemocaoDeVirusCuritibaRoute = RemocaoDeVirusCuritibaRouteImport.update({
  id: '/remocao-de-virus-curitiba',
  path: '/remocao-de-virus-curitiba',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaDosDadosRoute = SegurancaDosDadosRouteImport.update({
  id: '/seguranca-dos-dados',
  path: '/seguranca-dos-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const SejaPatrocinadorRoute = SejaPatrocinadorRouteImport.update({
  id: '/seja-patrocinador',
  path: '/seja-patrocinador',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusAnunciosRoute = StatusAnunciosRouteImport.update({
  id: '/status-anuncios',
  path: '/status-anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusDaOrdemDeServicoRoute = StatusDaOrdemDeServicoRouteImport.update({
  id: '/status-da-ordem-de-servico',
  path: '/status-da-ordem-de-servico',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusOsRoute = StatusOsRouteImport.update({
  id: '/status-os',
  path: '/status-os',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteTecnicoRemotoRoute = SuporteTecnicoRemotoRouteImport.update({
  id: '/suporte-tecnico-remoto',
  path: '/suporte-tecnico-remoto',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosOrcamentoRoute = TermosOrcamentoRouteImport.update({
  id: '/termos-orcamento',
  path: '/termos-orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosOrcamentoPreAprovadoRoute =
  TermosOrcamentoPreAprovadoRouteImport.update({
    id: '/termos-orcamento-pre-aprovado',
    path: '/termos-orcamento-pre-aprovado',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermosUsoRoute = TermosUsoRouteImport.update({
  id: '/termos-uso',
  path: '/termos-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const TriagemPreviewRoute = TriagemPreviewRouteImport.update({
  id: '/triagem-preview',
  path: '/triagem-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeMemoriaRamCuritibaRoute =
  UpgradeMemoriaRamCuritibaRouteImport.update({
    id: '/upgrade-memoria-ram-curitiba',
    path: '/upgrade-memoria-ram-curitiba',
    getParentRoute: () => rootRouteImport,
  } as any)
const UpgradeSsdCuritibaRoute = UpgradeSsdCuritibaRouteImport.update({
  id: '/upgrade-ssd-curitiba',
  path: '/upgrade-ssd-curitiba',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoNacionalIndexRoute =
  AtendimentoNacionalIndexRouteImport.update({
    id: '/atendimento-nacional/',
    path: '/atendimento-nacional/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AtendimentoNacionalSlugRoute = AtendimentoNacionalSlugRouteImport.update({
  id: '/atendimento-nacional/$slug',
  path: '/atendimento-nacional/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasComoEscolherUmaWorkstationRoute =
  GuiasComoEscolherUmaWorkstationRouteImport.update({
    id: '/guias/como-escolher-uma-workstation',
    path: '/guias/como-escolher-uma-workstation',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuiasOrganizacaoDeTiParaPequenosEscritoriosRoute =
  GuiasOrganizacaoDeTiParaPequenosEscritoriosRouteImport.update({
    id: '/guias/organizacao-de-ti-para-pequenos-escritorios',
    path: '/guias/organizacao-de-ti-para-pequenos-escritorios',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperacaoManifestoDeProvasRoute =
  OperacaoManifestoDeProvasRouteImport.update({
    id: '/operacao/manifesto-de-provas',
    path: '/operacao/manifesto-de-provas',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperacaoMensagensProntasRoute =
  OperacaoMensagensProntasRouteImport.update({
    id: '/operacao/mensagens-prontas',
    path: '/operacao/mensagens-prontas',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperacaoPainelConversaoRoute = OperacaoPainelConversaoRouteImport.update({
  id: '/operacao/painel-conversao',
  path: '/operacao/painel-conversao',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoPainelGoogleBusinessRoute =
  OperacaoPainelGoogleBusinessRouteImport.update({
    id: '/operacao/painel-google-business',
    path: '/operacao/painel-google-business',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegioesIndexRoute = RegioesIndexRouteImport.update({
  id: '/regioes/',
  path: '/regioes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/servicos/$slug',
  path: '/servicos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosBackupParaEmpresasRoute =
  ServicosBackupParaEmpresasRouteImport.update({
    id: '/servicos/backup-para-empresas',
    path: '/servicos/backup-para-empresas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosConfiguracaoWifiCuritibaRoute =
  ServicosConfiguracaoWifiCuritibaRouteImport.update({
    id: '/servicos/configuracao-wifi-curitiba',
    path: '/servicos/configuracao-wifi-curitiba',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosConsertoDeSomEAudioCuritibaRoute =
  ServicosConsertoDeSomEAudioCuritibaRouteImport.update({
    id: '/servicos/conserto-de-som-e-audio-curitiba',
    path: '/servicos/conserto-de-som-e-audio-curitiba',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosConsertoDeTelevisaoRoute =
  ServicosConsertoDeTelevisaoRouteImport.update({
    id: '/servicos/conserto-de-televisao',
    path: '/servicos/conserto-de-televisao',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosConsertoDeTvRoute = ServicosConsertoDeTvRouteImport.update({
  id: '/servicos/conserto-de-tv',
  path: '/servicos/conserto-de-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosConsertoTvRoute = ServicosConsertoTvRouteImport.update({
  id: '/servicos/conserto-tv',
  path: '/servicos/conserto-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosManutencaoPreventivaEmpresasRoute =
  ServicosManutencaoPreventivaEmpresasRouteImport.update({
    id: '/servicos/manutencao-preventiva-empresas',
    path: '/servicos/manutencao-preventiva-empresas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosRedesEWifiRoute = ServicosRedesEWifiRouteImport.update({
  id: '/servicos/redes-e-wifi',
  path: '/servicos/redes-e-wifi',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosReparoSmartTvCuritibaRoute =
  ServicosReparoSmartTvCuritibaRouteImport.update({
    id: '/servicos/reparo-smart-tv-curitiba',
    path: '/servicos/reparo-smart-tv-curitiba',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosSuporteTecnicoEmpresarialRoute =
  ServicosSuporteTecnicoEmpresarialRouteImport.update({
    id: '/servicos/suporte-tecnico-empresarial',
    path: '/servicos/suporte-tecnico-empresarial',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosTrocaDeTelaTvCuritibaRoute =
  ServicosTrocaDeTelaTvCuritibaRouteImport.update({
    id: '/servicos/troca-de-tela-tv-curitiba',
    path: '/servicos/troca-de-tela-tv-curitiba',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesIndexRoute = SolucoesIndexRouteImport.update({
  id: '/solucoes/',
  path: '/solucoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesSlugRoute = SolucoesSlugRouteImport.update({
  id: '/solucoes/$slug',
  path: '/solucoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoNacionalCityBairroRoute =
  AtendimentoNacionalCityBairroRouteImport.update({
    id: '/atendimento-nacional/$city/$bairro',
    path: '/atendimento-nacional/$city/$bairro',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCategoriaSlugRoute = BlogCategoriaSlugRouteImport.update({
  id: '/blog/categoria/$slug',
  path: '/blog/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RegioesCityIndexRoute = RegioesCityIndexRouteImport.update({
  id: '/regioes/$city/',
  path: '/regioes/$city/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegioesCityNeighborhoodRoute = RegioesCityNeighborhoodRouteImport.update({
  id: '/regioes/$city/$neighborhood',
  path: '/regioes/$city/$neighborhood',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicoEmCityServiceRoute = ServicoEmCityServiceRouteImport.update({
  id: '/servico-em/$city/$service',
  path: '/servico-em/$city/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosServicoCuritibaRoute = ServicosServicoCuritibaRouteImport.update({
  id: '/servicos/$servico/curitiba',
  path: '/servicos/$servico/curitiba',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosConfiguracaoWifiCidadeRoute =
  ServicosConfiguracaoWifiCidadeRouteImport.update({
    id: '/servicos/configuracao-wifi/$cidade',
    path: '/servicos/configuracao-wifi/$cidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosPcGamerComoFuncionaRoute =
  ServicosPcGamerComoFuncionaRouteImport.update({
    id: '/servicos/pc-gamer/como-funciona',
    path: '/servicos/pc-gamer/como-funciona',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosReparoSmartTvCidadeRoute =
  ServicosReparoSmartTvCidadeRouteImport.update({
    id: '/servicos/reparo-smart-tv/$cidade',
    path: '/servicos/reparo-smart-tv/$cidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosTrocaDeTelaTvCidadeRoute =
  ServicosTrocaDeTelaTvCidadeRouteImport.update({
    id: '/servicos/troca-de-tela-tv/$cidade',
    path: '/servicos/troca-de-tela-tv/$cidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicoEmNacionalCityBairroServiceRoute =
  ServicoEmNacionalCityBairroServiceRouteImport.update({
    id: '/servico-em-nacional/$city/$bairro/$service',
    path: '/servico-em-nacional/$city/$bairro/$service',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosConfiguracaoWifiCuritibaBairroRoute =
  ServicosConfiguracaoWifiCuritibaBairroRouteImport.update({
    id: '/servicos/configuracao-wifi/curitiba/$bairro',
    path: '/servicos/configuracao-wifi/curitiba/$bairro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosConfiguracaoWifiPinhaisBairroRoute =
  ServicosConfiguracaoWifiPinhaisBairroRouteImport.update({
    id: '/servicos/configuracao-wifi/pinhais/$bairro',
    path: '/servicos/configuracao-wifi/pinhais/$bairro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosConfiguracaoWifiSaoJoseDosPinhaisBairroRoute =
  ServicosConfiguracaoWifiSaoJoseDosPinhaisBairroRouteImport.update({
    id: '/servicos/configuracao-wifi/sao-jose-dos-pinhais/$bairro',
    path: '/servicos/configuracao-wifi/sao-jose-dos-pinhais/$bairro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosReparoSmartTvCuritibaBairroRoute =
  ServicosReparoSmartTvCuritibaBairroRouteImport.update({
    id: '/servicos/reparo-smart-tv/curitiba/$bairro',
    path: '/servicos/reparo-smart-tv/curitiba/$bairro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosReparoSmartTvPinhaisBairroRoute =
  ServicosReparoSmartTvPinhaisBairroRouteImport.update({
    id: '/servicos/reparo-smart-tv/pinhais/$bairro',
    path: '/servicos/reparo-smart-tv/pinhais/$bairro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosReparoSmartTvSaoJoseDosPinhaisBairroRoute =
  ServicosReparoSmartTvSaoJoseDosPinhaisBairroRouteImport.update({
    id: '/servicos/reparo-smart-tv/sao-jose-dos-pinhais/$bairro',
    path: '/servicos/reparo-smart-tv/sao-jose-dos-pinhais/$bairro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosTrocaDeTelaTvPinhaisBairroRoute =
  ServicosTrocaDeTelaTvPinhaisBairroRouteImport.update({
    id: '/servicos/troca-de-tela-tv/pinhais/$bairro',
    path: '/servicos/troca-de-tela-tv/pinhais/$bairro',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abrir-os': typeof AbrirOsRoute
  '/admin': typeof AdminRoute
  '/anuncie': typeof AnuncieRoute
  '/area-de-atendimento-curitiba': typeof AreaDeAtendimentoCuritibaRoute
  '/areas-atendidas': typeof AreasAtendidasRoute
  '/assistencia-tecnica': typeof AssistenciaTecnicaRoute
  '/assistencia-tecnica-curitiba': typeof AssistenciaTecnicaCuritibaRoute
  '/assistencia-tecnica-empresas-curitiba': typeof AssistenciaTecnicaEmpresasCuritibaRoute
  '/atendimento-urgente': typeof AtendimentoUrgenteRoute
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/avaliar': typeof AvaliarRoute
  '/busca': typeof BuscaRoute
  '/checklist-publicacao': typeof ChecklistPublicacaoRoute
  '/checklists-de-reparo': typeof ChecklistsDeReparoRoute
  '/como-avaliar': typeof ComoAvaliarRoute
  '/como-escolher-tecnico-preco-prazo': typeof ComoEscolherTecnicoPrecoPrazoRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/conserto-de-notebook-curitiba': typeof ConsertoDeNotebookCuritibaRoute
  '/consultar-os': typeof ConsultarOsRoute
  '/contato': typeof ContatoRoute
  '/creditos-de-imagens': typeof CreditosDeImagensRoute
  '/dados-da-empresa': typeof DadosDaEmpresaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/empresa-de-ti-curitiba': typeof EmpresaDeTiCuritibaRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/faq': typeof FaqRoute
  '/formatacao-de-computador-curitiba': typeof FormatacaoDeComputadorCuritibaRoute
  '/garantia-e-cobertura': typeof GarantiaECoberturaRoute
  '/gestor-responsavel': typeof GestorResponsavelRoute
  '/guia-tecnico-informatica': typeof GuiaTecnicoInformaticaRoute
  '/obrigado': typeof ObrigadoRoute
  '/ordem-de-servico': typeof OrdemDeServicoRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/politica-de-anuncios': typeof PoliticaDeAnunciosRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-pecas-do-cliente': typeof PoliticaDePecasDoClienteRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/precos': typeof PrecosRoute
  '/precos-e-politicas': typeof PrecosEPoliticasRoute
  '/processo-de-atendimento': typeof ProcessoDeAtendimentoRoute
  '/publicidade': typeof PublicidadeRoute
  '/remocao-de-virus-curitiba': typeof RemocaoDeVirusCuritibaRoute
  '/seguranca-dos-dados': typeof SegurancaDosDadosRoute
  '/seja-patrocinador': typeof SejaPatrocinadorRoute
  '/sobre': typeof SobreRoute
  '/status-anuncios': typeof StatusAnunciosRoute
  '/status-da-ordem-de-servico': typeof StatusDaOrdemDeServicoRoute
  '/status-os': typeof StatusOsRoute
  '/suporte-tecnico-remoto': typeof SuporteTecnicoRemotoRoute
  '/termos-orcamento': typeof TermosOrcamentoRoute
  '/termos-orcamento-pre-aprovado': typeof TermosOrcamentoPreAprovadoRoute
  '/termos-uso': typeof TermosUsoRoute
  '/triagem-preview': typeof TriagemPreviewRoute
  '/upgrade-memoria-ram-curitiba': typeof UpgradeMemoriaRamCuritibaRoute
  '/upgrade-ssd-curitiba': typeof UpgradeSsdCuritibaRoute
  '/atendimento-nacional/$slug': typeof AtendimentoNacionalSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guias/como-escolher-uma-workstation': typeof GuiasComoEscolherUmaWorkstationRoute
  '/guias/organizacao-de-ti-para-pequenos-escritorios': typeof GuiasOrganizacaoDeTiParaPequenosEscritoriosRoute
  '/operacao/manifesto-de-provas': typeof OperacaoManifestoDeProvasRoute
  '/operacao/mensagens-prontas': typeof OperacaoMensagensProntasRoute
  '/operacao/painel-conversao': typeof OperacaoPainelConversaoRoute
  '/operacao/painel-google-business': typeof OperacaoPainelGoogleBusinessRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/servicos/backup-para-empresas': typeof ServicosBackupParaEmpresasRoute
  '/servicos/configuracao-wifi-curitiba': typeof ServicosConfiguracaoWifiCuritibaRoute
  '/servicos/conserto-de-som-e-audio-curitiba': typeof ServicosConsertoDeSomEAudioCuritibaRoute
  '/servicos/conserto-de-televisao': typeof ServicosConsertoDeTelevisaoRoute
  '/servicos/conserto-de-tv': typeof ServicosConsertoDeTvRoute
  '/servicos/conserto-tv': typeof ServicosConsertoTvRoute
  '/servicos/manutencao-preventiva-empresas': typeof ServicosManutencaoPreventivaEmpresasRoute
  '/servicos/redes-e-wifi': typeof ServicosRedesEWifiRoute
  '/servicos/reparo-smart-tv-curitiba': typeof ServicosReparoSmartTvCuritibaRoute
  '/servicos/suporte-tecnico-empresarial': typeof ServicosSuporteTecnicoEmpresarialRoute
  '/servicos/troca-de-tela-tv-curitiba': typeof ServicosTrocaDeTelaTvCuritibaRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/atendimento-nacional/': typeof AtendimentoNacionalIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/regioes/': typeof RegioesIndexRoute
  '/servicos/': typeof ServicosIndexRoute
  '/solucoes/': typeof SolucoesIndexRoute
  '/atendimento-nacional/$city/$bairro': typeof AtendimentoNacionalCityBairroRoute
  '/blog/categoria/$slug': typeof BlogCategoriaSlugRoute
  '/regioes/$city/$neighborhood': typeof RegioesCityNeighborhoodRoute
  '/servico-em/$city/$service': typeof ServicoEmCityServiceRoute
  '/servicos/$servico/curitiba': typeof ServicosServicoCuritibaRoute
  '/servicos/configuracao-wifi/$cidade': typeof ServicosConfiguracaoWifiCidadeRoute
  '/servicos/pc-gamer/como-funciona': typeof ServicosPcGamerComoFuncionaRoute
  '/servicos/reparo-smart-tv/$cidade': typeof ServicosReparoSmartTvCidadeRoute
  '/servicos/troca-de-tela-tv/$cidade': typeof ServicosTrocaDeTelaTvCidadeRoute
  '/regioes/$city/': typeof RegioesCityIndexRoute
  '/servico-em-nacional/$city/$bairro/$service': typeof ServicoEmNacionalCityBairroServiceRoute
  '/servicos/configuracao-wifi/curitiba/$bairro': typeof ServicosConfiguracaoWifiCuritibaBairroRoute
  '/servicos/configuracao-wifi/pinhais/$bairro': typeof ServicosConfiguracaoWifiPinhaisBairroRoute
  '/servicos/configuracao-wifi/sao-jose-dos-pinhais/$bairro': typeof ServicosConfiguracaoWifiSaoJoseDosPinhaisBairroRoute
  '/servicos/reparo-smart-tv/curitiba/$bairro': typeof ServicosReparoSmartTvCuritibaBairroRoute
  '/servicos/reparo-smart-tv/pinhais/$bairro': typeof ServicosReparoSmartTvPinhaisBairroRoute
  '/servicos/reparo-smart-tv/sao-jose-dos-pinhais/$bairro': typeof ServicosReparoSmartTvSaoJoseDosPinhaisBairroRoute
  '/servicos/troca-de-tela-tv/pinhais/$bairro': typeof ServicosTrocaDeTelaTvPinhaisBairroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abrir-os': typeof AbrirOsRoute
  '/admin': typeof AdminRoute
  '/anuncie': typeof AnuncieRoute
  '/area-de-atendimento-curitiba': typeof AreaDeAtendimentoCuritibaRoute
  '/areas-atendidas': typeof AreasAtendidasRoute
  '/assistencia-tecnica': typeof AssistenciaTecnicaRoute
  '/assistencia-tecnica-curitiba': typeof AssistenciaTecnicaCuritibaRoute
  '/assistencia-tecnica-empresas-curitiba': typeof AssistenciaTecnicaEmpresasCuritibaRoute
  '/atendimento-urgente': typeof AtendimentoUrgenteRoute
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/avaliar': typeof AvaliarRoute
  '/busca': typeof BuscaRoute
  '/checklist-publicacao': typeof ChecklistPublicacaoRoute
  '/checklists-de-reparo': typeof ChecklistsDeReparoRoute
  '/como-avaliar': typeof ComoAvaliarRoute
  '/como-escolher-tecnico-preco-prazo': typeof ComoEscolherTecnicoPrecoPrazoRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/conserto-de-notebook-curitiba': typeof ConsertoDeNotebookCuritibaRoute
  '/consultar-os': typeof ConsultarOsRoute
  '/contato': typeof ContatoRoute
  '/creditos-de-imagens': typeof CreditosDeImagensRoute
  '/dados-da-empresa': typeof DadosDaEmpresaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/empresa-de-ti-curitiba': typeof EmpresaDeTiCuritibaRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/faq': typeof FaqRoute
  '/formatacao-de-computador-curitiba': typeof FormatacaoDeComputadorCuritibaRoute
  '/garantia-e-cobertura': typeof GarantiaECoberturaRoute
  '/gestor-responsavel': typeof GestorResponsavelRoute
  '/guia-tecnico-informatica': typeof GuiaTecnicoInformaticaRoute
  '/obrigado': typeof ObrigadoRoute
  '/ordem-de-servico': typeof OrdemDeServicoRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/politica-de-anuncios': typeof PoliticaDeAnunciosRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-pecas-do-cliente': typeof PoliticaDePecasDoClienteRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/precos': typeof PrecosRoute
  '/precos-e-politicas': typeof PrecosEPoliticasRoute
  '/processo-de-atendimento': typeof ProcessoDeAtendimentoRoute
  '/publicidade': typeof PublicidadeRoute
  '/remocao-de-virus-curitiba': typeof RemocaoDeVirusCuritibaRoute
  '/seguranca-dos-dados': typeof SegurancaDosDadosRoute
  '/seja-patrocinador': typeof SejaPatrocinadorRoute
  '/sobre': typeof SobreRoute
  '/status-anuncios': typeof StatusAnunciosRoute
  '/status-da-ordem-de-servico': typeof StatusDaOrdemDeServicoRoute
  '/status-os': typeof StatusOsRoute
  '/suporte-tecnico-remoto': typeof SuporteTecnicoRemotoRoute
  '/termos-orcamento': typeof TermosOrcamentoRoute
  '/termos-orcamento-pre-aprovado': typeof TermosOrcamentoPreAprovadoRoute
  '/termos-uso': typeof TermosUsoRoute
  '/triagem-preview': typeof TriagemPreviewRoute
  '/upgrade-memoria-ram-curitiba': typeof UpgradeMemoriaRamCuritibaRoute
  '/upgrade-ssd-curitiba': typeof UpgradeSsdCuritibaRoute
  '/atendimento-nacional/$slug': typeof AtendimentoNacionalSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guias/como-escolher-uma-workstation': typeof GuiasComoEscolherUmaWorkstationRoute
  '/guias/organizacao-de-ti-para-pequenos-escritorios': typeof GuiasOrganizacaoDeTiParaPequenosEscritoriosRoute
  '/operacao/manifesto-de-provas': typeof OperacaoManifestoDeProvasRoute
  '/operacao/mensagens-prontas': typeof OperacaoMensagensProntasRoute
  '/operacao/painel-conversao': typeof OperacaoPainelConversaoRoute
  '/operacao/painel-google-business': typeof OperacaoPainelGoogleBusinessRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/servicos/backup-para-empresas': typeof ServicosBackupParaEmpresasRoute
  '/servicos/configuracao-wifi-curitiba': typeof ServicosConfiguracaoWifiCuritibaRoute
  '/servicos/conserto-de-som-e-audio-curitiba': typeof ServicosConsertoDeSomEAudioCuritibaRoute
  '/servicos/conserto-de-televisao': typeof ServicosConsertoDeTelevisaoRoute
  '/servicos/conserto-de-tv': typeof ServicosConsertoDeTvRoute
  '/servicos/conserto-tv': typeof ServicosConsertoTvRoute
  '/servicos/manutencao-preventiva-empresas': typeof ServicosManutencaoPreventivaEmpresasRoute
  '/servicos/redes-e-wifi': typeof ServicosRedesEWifiRoute
  '/servicos/reparo-smart-tv-curitiba': typeof ServicosReparoSmartTvCuritibaRoute
  '/servicos/suporte-tecnico-empresarial': typeof ServicosSuporteTecnicoEmpresarialRoute
  '/servicos/troca-de-tela-tv-curitiba': typeof ServicosTrocaDeTelaTvCuritibaRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/atendimento-nacional': typeof AtendimentoNacionalIndexRoute
  '/blog': typeof BlogIndexRoute
  '/regioes': typeof RegioesIndexRoute
  '/servicos': typeof ServicosIndexRoute
  '/solucoes': typeof SolucoesIndexRoute
  '/atendimento-nacional/$city/$bairro': typeof AtendimentoNacionalCityBairroRoute
  '/blog/categoria/$slug': typeof BlogCategoriaSlugRoute
  '/regioes/$city/$neighborhood': typeof RegioesCityNeighborhoodRoute
  '/servico-em/$city/$service': typeof ServicoEmCityServiceRoute
  '/servicos/$servico/curitiba': typeof ServicosServicoCuritibaRoute
  '/servicos/configuracao-wifi/$cidade': typeof ServicosConfiguracaoWifiCidadeRoute
  '/servicos/pc-gamer/como-funciona': typeof ServicosPcGamerComoFuncionaRoute
  '/servicos/reparo-smart-tv/$cidade': typeof ServicosReparoSmartTvCidadeRoute
  '/servicos/troca-de-tela-tv/$cidade': typeof ServicosTrocaDeTelaTvCidadeRoute
  '/regioes/$city': typeof RegioesCityIndexRoute
  '/servico-em-nacional/$city/$bairro/$service': typeof ServicoEmNacionalCityBairroServiceRoute
  '/servicos/configuracao-wifi/curitiba/$bairro': typeof ServicosConfiguracaoWifiCuritibaBairroRoute
  '/servicos/configuracao-wifi/pinhais/$bairro': typeof ServicosConfiguracaoWifiPinhaisBairroRoute
  '/servicos/configuracao-wifi/sao-jose-dos-pinhais/$bairro': typeof ServicosConfiguracaoWifiSaoJoseDosPinhaisBairroRoute
  '/servicos/reparo-smart-tv/curitiba/$bairro': typeof ServicosReparoSmartTvCuritibaBairroRoute
  '/servicos/reparo-smart-tv/pinhais/$bairro': typeof ServicosReparoSmartTvPinhaisBairroRoute
  '/servicos/reparo-smart-tv/sao-jose-dos-pinhais/$bairro': typeof ServicosReparoSmartTvSaoJoseDosPinhaisBairroRoute
  '/servicos/troca-de-tela-tv/pinhais/$bairro': typeof ServicosTrocaDeTelaTvPinhaisBairroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abrir-os': typeof AbrirOsRoute
  '/admin': typeof AdminRoute
  '/anuncie': typeof AnuncieRoute
  '/area-de-atendimento-curitiba': typeof AreaDeAtendimentoCuritibaRoute
  '/areas-atendidas': typeof AreasAtendidasRoute
  '/assistencia-tecnica': typeof AssistenciaTecnicaRoute
  '/assistencia-tecnica-curitiba': typeof AssistenciaTecnicaCuritibaRoute
  '/assistencia-tecnica-empresas-curitiba': typeof AssistenciaTecnicaEmpresasCuritibaRoute
  '/atendimento-urgente': typeof AtendimentoUrgenteRoute
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/avaliar': typeof AvaliarRoute
  '/busca': typeof BuscaRoute
  '/checklist-publicacao': typeof ChecklistPublicacaoRoute
  '/checklists-de-reparo': typeof ChecklistsDeReparoRoute
  '/como-avaliar': typeof ComoAvaliarRoute
  '/como-escolher-tecnico-preco-prazo': typeof ComoEscolherTecnicoPrecoPrazoRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/conserto-de-notebook-curitiba': typeof ConsertoDeNotebookCuritibaRoute
  '/consultar-os': typeof ConsultarOsRoute
  '/contato': typeof ContatoRoute
  '/creditos-de-imagens': typeof CreditosDeImagensRoute
  '/dados-da-empresa': typeof DadosDaEmpresaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/empresa-de-ti-curitiba': typeof EmpresaDeTiCuritibaRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/faq': typeof FaqRoute
  '/formatacao-de-computador-curitiba': typeof FormatacaoDeComputadorCuritibaRoute
  '/garantia-e-cobertura': typeof GarantiaECoberturaRoute
  '/gestor-responsavel': typeof GestorResponsavelRoute
  '/guia-tecnico-informatica': typeof GuiaTecnicoInformaticaRoute
  '/obrigado': typeof ObrigadoRoute
  '/ordem-de-servico': typeof OrdemDeServicoRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/politica-de-anuncios': typeof PoliticaDeAnunciosRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-pecas-do-cliente': typeof PoliticaDePecasDoClienteRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/precos': typeof PrecosRoute
  '/precos-e-politicas': typeof PrecosEPoliticasRoute
  '/processo-de-atendimento': typeof ProcessoDeAtendimentoRoute
  '/publicidade': typeof PublicidadeRoute
  '/remocao-de-virus-curitiba': typeof RemocaoDeVirusCuritibaRoute
  '/seguranca-dos-dados': typeof SegurancaDosDadosRoute
  '/seja-patrocinador': typeof SejaPatrocinadorRoute
  '/sobre': typeof SobreRoute
  '/status-anuncios': typeof StatusAnunciosRoute
  '/status-da-ordem-de-servico': typeof StatusDaOrdemDeServicoRoute
  '/status-os': typeof StatusOsRoute
  '/suporte-tecnico-remoto': typeof SuporteTecnicoRemotoRoute
  '/termos-orcamento': typeof TermosOrcamentoRoute
  '/termos-orcamento-pre-aprovado': typeof TermosOrcamentoPreAprovadoRoute
  '/termos-uso': typeof TermosUsoRoute
  '/triagem-preview': typeof TriagemPreviewRoute
  '/upgrade-memoria-ram-curitiba': typeof UpgradeMemoriaRamCuritibaRoute
  '/upgrade-ssd-curitiba': typeof UpgradeSsdCuritibaRoute
  '/atendimento-nacional/$slug': typeof AtendimentoNacionalSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guias/como-escolher-uma-workstation': typeof GuiasComoEscolherUmaWorkstationRoute
  '/guias/organizacao-de-ti-para-pequenos-escritorios': typeof GuiasOrganizacaoDeTiParaPequenosEscritoriosRoute
  '/operacao/manifesto-de-provas': typeof OperacaoManifestoDeProvasRoute
  '/operacao/mensagens-prontas': typeof OperacaoMensagensProntasRoute
  '/operacao/painel-conversao': typeof OperacaoPainelConversaoRoute
  '/operacao/painel-google-business': typeof OperacaoPainelGoogleBusinessRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/servicos/backup-para-empresas': typeof ServicosBackupParaEmpresasRoute
  '/servicos/configuracao-wifi-curitiba': typeof ServicosConfiguracaoWifiCuritibaRoute
  '/servicos/conserto-de-som-e-audio-curitiba': typeof ServicosConsertoDeSomEAudioCuritibaRoute
  '/servicos/conserto-de-televisao': typeof ServicosConsertoDeTelevisaoRoute
  '/servicos/conserto-de-tv': typeof ServicosConsertoDeTvRoute
  '/servicos/conserto-tv': typeof ServicosConsertoTvRoute
  '/servicos/manutencao-preventiva-empresas': typeof ServicosManutencaoPreventivaEmpresasRoute
  '/servicos/redes-e-wifi': typeof ServicosRedesEWifiRoute
  '/servicos/reparo-smart-tv-curitiba': typeof ServicosReparoSmartTvCuritibaRoute
  '/servicos/suporte-tecnico-empresarial': typeof ServicosSuporteTecnicoEmpresarialRoute
  '/servicos/troca-de-tela-tv-curitiba': typeof ServicosTrocaDeTelaTvCuritibaRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/atendimento-nacional/': typeof AtendimentoNacionalIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/regioes/': typeof RegioesIndexRoute
  '/servicos/': typeof ServicosIndexRoute
  '/solucoes/': typeof SolucoesIndexRoute
  '/atendimento-nacional/$city/$bairro': typeof AtendimentoNacionalCityBairroRoute
  '/blog/categoria/$slug': typeof BlogCategoriaSlugRoute
  '/regioes/$city/$neighborhood': typeof RegioesCityNeighborhoodRoute
  '/servico-em/$city/$service': typeof ServicoEmCityServiceRoute
  '/servicos/$servico/curitiba': typeof ServicosServicoCuritibaRoute
  '/servicos/configuracao-wifi/$cidade': typeof ServicosConfiguracaoWifiCidadeRoute
  '/servicos/pc-gamer/como-funciona': typeof ServicosPcGamerComoFuncionaRoute
  '/servicos/reparo-smart-tv/$cidade': typeof ServicosReparoSmartTvCidadeRoute
  '/servicos/troca-de-tela-tv/$cidade': typeof ServicosTrocaDeTelaTvCidadeRoute
  '/regioes/$city/': typeof RegioesCityIndexRoute
  '/servico-em-nacional/$city/$bairro/$service': typeof ServicoEmNacionalCityBairroServiceRoute
  '/servicos/configuracao-wifi/curitiba/$bairro': typeof ServicosConfiguracaoWifiCuritibaBairroRoute
  '/servicos/configuracao-wifi/pinhais/$bairro': typeof ServicosConfiguracaoWifiPinhaisBairroRoute
  '/servicos/configuracao-wifi/sao-jose-dos-pinhais/$bairro': typeof ServicosConfiguracaoWifiSaoJoseDosPinhaisBairroRoute
  '/servicos/reparo-smart-tv/curitiba/$bairro': typeof ServicosReparoSmartTvCuritibaBairroRoute
  '/servicos/reparo-smart-tv/pinhais/$bairro': typeof ServicosReparoSmartTvPinhaisBairroRoute
  '/servicos/reparo-smart-tv/sao-jose-dos-pinhais/$bairro': typeof ServicosReparoSmartTvSaoJoseDosPinhaisBairroRoute
  '/servicos/troca-de-tela-tv/pinhais/$bairro': typeof ServicosTrocaDeTelaTvPinhaisBairroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abrir-os'
    | '/admin'
    | '/anuncie'
    | '/area-de-atendimento-curitiba'
    | '/areas-atendidas'
    | '/assistencia-tecnica'
    | '/assistencia-tecnica-curitiba'
    | '/assistencia-tecnica-empresas-curitiba'
    | '/atendimento-urgente'
    | '/auth'
    | '/avaliacoes'
    | '/avaliar'
    | '/busca'
    | '/checklist-publicacao'
    | '/checklists-de-reparo'
    | '/como-avaliar'
    | '/como-escolher-tecnico-preco-prazo'
    | '/como-funciona'
    | '/conserto-de-notebook-curitiba'
    | '/consultar-os'
    | '/contato'
    | '/creditos-de-imagens'
    | '/dados-da-empresa'
    | '/diagnostico'
    | '/diagnostics'
    | '/empresa-de-ti-curitiba'
    | '/exclusao-de-dados'
    | '/faq'
    | '/formatacao-de-computador-curitiba'
    | '/garantia-e-cobertura'
    | '/gestor-responsavel'
    | '/guia-tecnico-informatica'
    | '/obrigado'
    | '/ordem-de-servico'
    | '/patrocinadores'
    | '/politica-de-anuncios'
    | '/politica-de-cookies'
    | '/politica-de-pecas-do-cliente'
    | '/politica-de-privacidade'
    | '/politica-privacidade'
    | '/precos'
    | '/precos-e-politicas'
    | '/processo-de-atendimento'
    | '/publicidade'
    | '/remocao-de-virus-curitiba'
    | '/seguranca-dos-dados'
    | '/seja-patrocinador'
    | '/sobre'
    | '/status-anuncios'
    | '/status-da-ordem-de-servico'
    | '/status-os'
    | '/suporte-tecnico-remoto'
    | '/termos-orcamento'
    | '/termos-orcamento-pre-aprovado'
    | '/termos-uso'
    | '/triagem-preview'
    | '/upgrade-memoria-ram-curitiba'
    | '/upgrade-ssd-curitiba'
    | '/atendimento-nacional/$slug'
    | '/blog/$slug'
    | '/guias/como-escolher-uma-workstation'
    | '/guias/organizacao-de-ti-para-pequenos-escritorios'
    | '/operacao/manifesto-de-provas'
    | '/operacao/mensagens-prontas'
    | '/operacao/painel-conversao'
    | '/operacao/painel-google-business'
    | '/servicos/$slug'
    | '/servicos/backup-para-empresas'
    | '/servicos/configuracao-wifi-curitiba'
    | '/servicos/conserto-de-som-e-audio-curitiba'
    | '/servicos/conserto-de-televisao'
    | '/servicos/conserto-de-tv'
    | '/servicos/conserto-tv'
    | '/servicos/manutencao-preventiva-empresas'
    | '/servicos/redes-e-wifi'
    | '/servicos/reparo-smart-tv-curitiba'
    | '/servicos/suporte-tecnico-empresarial'
    | '/servicos/troca-de-tela-tv-curitiba'
    | '/solucoes/$slug'
    | '/atendimento-nacional/'
    | '/blog/'
    | '/regioes/'
    | '/servicos/'
    | '/solucoes/'
    | '/atendimento-nacional/$city/$bairro'
    | '/blog/categoria/$slug'
    | '/regioes/$city/$neighborhood'
    | '/servico-em/$city/$service'
    | '/servicos/$servico/curitiba'
    | '/servicos/configuracao-wifi/$cidade'
    | '/servicos/pc-gamer/como-funciona'
    | '/servicos/reparo-smart-tv/$cidade'
    | '/servicos/troca-de-tela-tv/$cidade'
    | '/regioes/$city/'
    | '/servico-em-nacional/$city/$bairro/$service'
    | '/servicos/configuracao-wifi/curitiba/$bairro'
    | '/servicos/configuracao-wifi/pinhais/$bairro'
    | '/servicos/configuracao-wifi/sao-jose-dos-pinhais/$bairro'
    | '/servicos/reparo-smart-tv/curitiba/$bairro'
    | '/servicos/reparo-smart-tv/pinhais/$bairro'
    | '/servicos/reparo-smart-tv/sao-jose-dos-pinhais/$bairro'
    | '/servicos/troca-de-tela-tv/pinhais/$bairro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abrir-os'
    | '/admin'
    | '/anuncie'
    | '/area-de-atendimento-curitiba'
    | '/areas-atendidas'
    | '/assistencia-tecnica'
    | '/assistencia-tecnica-curitiba'
    | '/assistencia-tecnica-empresas-curitiba'
    | '/atendimento-urgente'
    | '/auth'
    | '/avaliacoes'
    | '/avaliar'
    | '/busca'
    | '/checklist-publicacao'
    | '/checklists-de-reparo'
    | '/como-avaliar'
    | '/como-escolher-tecnico-preco-prazo'
    | '/como-funciona'
    | '/conserto-de-notebook-curitiba'
    | '/consultar-os'
    | '/contato'
    | '/creditos-de-imagens'
    | '/dados-da-empresa'
    | '/diagnostico'
    | '/diagnostics'
    | '/empresa-de-ti-curitiba'
    | '/exclusao-de-dados'
    | '/faq'
    | '/formatacao-de-computador-curitiba'
    | '/garantia-e-cobertura'
    | '/gestor-responsavel'
    | '/guia-tecnico-informatica'
    | '/obrigado'
    | '/ordem-de-servico'
    | '/patrocinadores'
    | '/politica-de-anuncios'
    | '/politica-de-cookies'
    | '/politica-de-pecas-do-cliente'
    | '/politica-de-privacidade'
    | '/politica-privacidade'
    | '/precos'
    | '/precos-e-politicas'
    | '/processo-de-atendimento'
    | '/publicidade'
    | '/remocao-de-virus-curitiba'
    | '/seguranca-dos-dados'
    | '/seja-patrocinador'
    | '/sobre'
    | '/status-anuncios'
    | '/status-da-ordem-de-servico'
    | '/status-os'
    | '/suporte-tecnico-remoto'
    | '/termos-orcamento'
    | '/termos-orcamento-pre-aprovado'
    | '/termos-uso'
    | '/triagem-preview'
    | '/upgrade-memoria-ram-curitiba'
    | '/upgrade-ssd-curitiba'
    | '/atendimento-nacional/$slug'
    | '/blog/$slug'
    | '/guias/como-escolher-uma-workstation'
    | '/guias/organizacao-de-ti-para-pequenos-escritorios'
    | '/operacao/manifesto-de-provas'
    | '/operacao/mensagens-prontas'
    | '/operacao/painel-conversao'
    | '/operacao/painel-google-business'
    | '/servicos/$slug'
    | '/servicos/backup-para-empresas'
    | '/servicos/configuracao-wifi-curitiba'
    | '/servicos/conserto-de-som-e-audio-curitiba'
    | '/servicos/conserto-de-televisao'
    | '/servicos/conserto-de-tv'
    | '/servicos/conserto-tv'
    | '/servicos/manutencao-preventiva-empresas'
    | '/servicos/redes-e-wifi'
    | '/servicos/reparo-smart-tv-curitiba'
    | '/servicos/suporte-tecnico-empresarial'
    | '/servicos/troca-de-tela-tv-curitiba'
    | '/solucoes/$slug'
    | '/atendimento-nacional'
    | '/blog'
    | '/regioes'
    | '/servicos'
    | '/solucoes'
    | '/atendimento-nacional/$city/$bairro'
    | '/blog/categoria/$slug'
    | '/regioes/$city/$neighborhood'
    | '/servico-em/$city/$service'
    | '/servicos/$servico/curitiba'
    | '/servicos/configuracao-wifi/$cidade'
    | '/servicos/pc-gamer/como-funciona'
    | '/servicos/reparo-smart-tv/$cidade'
    | '/servicos/troca-de-tela-tv/$cidade'
    | '/regioes/$city'
    | '/servico-em-nacional/$city/$bairro/$service'
    | '/servicos/configuracao-wifi/curitiba/$bairro'
    | '/servicos/configuracao-wifi/pinhais/$bairro'
    | '/servicos/configuracao-wifi/sao-jose-dos-pinhais/$bairro'
    | '/servicos/reparo-smart-tv/curitiba/$bairro'
    | '/servicos/reparo-smart-tv/pinhais/$bairro'
    | '/servicos/reparo-smart-tv/sao-jose-dos-pinhais/$bairro'
    | '/servicos/troca-de-tela-tv/pinhais/$bairro'
  id:
    | '__root__'
    | '/'
    | '/abrir-os'
    | '/admin'
    | '/anuncie'
    | '/area-de-atendimento-curitiba'
    | '/areas-atendidas'
    | '/assistencia-tecnica'
    | '/assistencia-tecnica-curitiba'
    | '/assistencia-tecnica-empresas-curitiba'
    | '/atendimento-urgente'
    | '/auth'
    | '/avaliacoes'
    | '/avaliar'
    | '/busca'
    | '/checklist-publicacao'
    | '/checklists-de-reparo'
    | '/como-avaliar'
    | '/como-escolher-tecnico-preco-prazo'
    | '/como-funciona'
    | '/conserto-de-notebook-curitiba'
    | '/consultar-os'
    | '/contato'
    | '/creditos-de-imagens'
    | '/dados-da-empresa'
    | '/diagnostico'
    | '/diagnostics'
    | '/empresa-de-ti-curitiba'
    | '/exclusao-de-dados'
    | '/faq'
    | '/formatacao-de-computador-curitiba'
    | '/garantia-e-cobertura'
    | '/gestor-responsavel'
    | '/guia-tecnico-informatica'
    | '/obrigado'
    | '/ordem-de-servico'
    | '/patrocinadores'
    | '/politica-de-anuncios'
    | '/politica-de-cookies'
    | '/politica-de-pecas-do-cliente'
    | '/politica-de-privacidade'
    | '/politica-privacidade'
    | '/precos'
    | '/precos-e-politicas'
    | '/processo-de-atendimento'
    | '/publicidade'
    | '/remocao-de-virus-curitiba'
    | '/seguranca-dos-dados'
    | '/seja-patrocinador'
    | '/sobre'
    | '/status-anuncios'
    | '/status-da-ordem-de-servico'
    | '/status-os'
    | '/suporte-tecnico-remoto'
    | '/termos-orcamento'
    | '/termos-orcamento-pre-aprovado'
    | '/termos-uso'
    | '/triagem-preview'
    | '/upgrade-memoria-ram-curitiba'
    | '/upgrade-ssd-curitiba'
    | '/atendimento-nacional/$slug'
    | '/blog/$slug'
    | '/guias/como-escolher-uma-workstation'
    | '/guias/organizacao-de-ti-para-pequenos-escritorios'
    | '/operacao/manifesto-de-provas'
    | '/operacao/mensagens-prontas'
    | '/operacao/painel-conversao'
    | '/operacao/painel-google-business'
    | '/servicos/$slug'
    | '/servicos/backup-para-empresas'
    | '/servicos/configuracao-wifi-curitiba'
    | '/servicos/conserto-de-som-e-audio-curitiba'
    | '/servicos/conserto-de-televisao'
    | '/servicos/conserto-de-tv'
    | '/servicos/conserto-tv'
    | '/servicos/manutencao-preventiva-empresas'
    | '/servicos/redes-e-wifi'
    | '/servicos/reparo-smart-tv-curitiba'
    | '/servicos/suporte-tecnico-empresarial'
    | '/servicos/troca-de-tela-tv-curitiba'
    | '/solucoes/$slug'
    | '/atendimento-nacional/'
    | '/blog/'
    | '/regioes/'
    | '/servicos/'
    | '/solucoes/'
    | '/atendimento-nacional/$city/$bairro'
    | '/blog/categoria/$slug'
    | '/regioes/$city/$neighborhood'
    | '/servico-em/$city/$service'
    | '/servicos/$servico/curitiba'
    | '/servicos/configuracao-wifi/$cidade'
    | '/servicos/pc-gamer/como-funciona'
    | '/servicos/reparo-smart-tv/$cidade'
    | '/servicos/troca-de-tela-tv/$cidade'
    | '/regioes/$city/'
    | '/servico-em-nacional/$city/$bairro/$service'
    | '/servicos/configuracao-wifi/curitiba/$bairro'
    | '/servicos/configuracao-wifi/pinhais/$bairro'
    | '/servicos/configuracao-wifi/sao-jose-dos-pinhais/$bairro'
    | '/servicos/reparo-smart-tv/curitiba/$bairro'
    | '/servicos/reparo-smart-tv/pinhais/$bairro'
    | '/servicos/reparo-smart-tv/sao-jose-dos-pinhais/$bairro'
    | '/servicos/troca-de-tela-tv/pinhais/$bairro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbrirOsRoute: typeof AbrirOsRoute
  AdminRoute: typeof AdminRoute
  AnuncieRoute: typeof AnuncieRoute
  AreaDeAtendimentoCuritibaRoute: typeof AreaDeAtendimentoCuritibaRoute
  AreasAtendidasRoute: typeof AreasAtendidasRoute
  AssistenciaTecnicaRoute: typeof AssistenciaTecnicaRoute
  AssistenciaTecnicaCuritibaRoute: typeof AssistenciaTecnicaCuritibaRoute
  AssistenciaTecnicaEmpresasCuritibaRoute: typeof AssistenciaTecnicaEmpresasCuritibaRoute
  AtendimentoUrgenteRoute: typeof AtendimentoUrgenteRoute
  AuthRoute: typeof AuthRoute
  AvaliacoesRoute: typeof AvaliacoesRoute
  AvaliarRoute: typeof AvaliarRoute
  BuscaRoute: typeof BuscaRoute
  ChecklistPublicacaoRoute: typeof ChecklistPublicacaoRoute
  ChecklistsDeReparoRoute: typeof ChecklistsDeReparoRoute
  ComoAvaliarRoute: typeof ComoAvaliarRoute
  ComoEscolherTecnicoPrecoPrazoRoute: typeof ComoEscolherTecnicoPrecoPrazoRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ConsertoDeNotebookCuritibaRoute: typeof ConsertoDeNotebookCuritibaRoute
  ConsultarOsRoute: typeof ConsultarOsRoute
  ContatoRoute: typeof ContatoRoute
  CreditosDeImagensRoute: typeof CreditosDeImagensRoute
  DadosDaEmpresaRoute: typeof DadosDaEmpresaRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  EmpresaDeTiCuritibaRoute: typeof EmpresaDeTiCuritibaRoute
  ExclusaoDeDadosRoute: typeof ExclusaoDeDadosRoute
  FaqRoute: typeof FaqRoute
  FormatacaoDeComputadorCuritibaRoute: typeof FormatacaoDeComputadorCuritibaRoute
  GarantiaECoberturaRoute: typeof GarantiaECoberturaRoute
  GestorResponsavelRoute: typeof GestorResponsavelRoute
  GuiaTecnicoInformaticaRoute: typeof GuiaTecnicoInformaticaRoute
  ObrigadoRoute: typeof ObrigadoRoute
  OrdemDeServicoRoute: typeof OrdemDeServicoRoute
  PatrocinadoresRoute: typeof PatrocinadoresRoute
  PoliticaDeAnunciosRoute: typeof PoliticaDeAnunciosRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePecasDoClienteRoute: typeof PoliticaDePecasDoClienteRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PoliticaPrivacidadeRoute: typeof PoliticaPrivacidadeRoute
  PrecosRoute: typeof PrecosRoute
  PrecosEPoliticasRoute: typeof PrecosEPoliticasRoute
  ProcessoDeAtendimentoRoute: typeof ProcessoDeAtendimentoRoute
  PublicidadeRoute: typeof PublicidadeRoute
  RemocaoDeVirusCuritibaRoute: typeof RemocaoDeVirusCuritibaRoute
  SegurancaDosDadosRoute: typeof SegurancaDosDadosRoute
  SejaPatrocinadorRoute: typeof SejaPatrocinadorRoute
  SobreRoute: typeof SobreRoute
  StatusAnunciosRoute: typeof StatusAnunciosRoute
  StatusDaOrdemDeServicoRoute: typeof StatusDaOrdemDeServicoRoute
  StatusOsRoute: typeof StatusOsRoute
  SuporteTecnicoRemotoRoute: typeof SuporteTecnicoRemotoRoute
  TermosOrcamentoRoute: typeof TermosOrcamentoRoute
  TermosOrcamentoPreAprovadoRoute: typeof TermosOrcamentoPreAprovadoRoute
  TermosUsoRoute: typeof TermosUsoRoute
  TriagemPreviewRoute: typeof TriagemPreviewRoute
  UpgradeMemoriaRamCuritibaRoute: typeof UpgradeMemoriaRamCuritibaRoute
  UpgradeSsdCuritibaRoute: typeof UpgradeSsdCuritibaRoute
  AtendimentoNacionalSlugRoute: typeof AtendimentoNacionalSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GuiasComoEscolherUmaWorkstationRoute: typeof GuiasComoEscolherUmaWorkstationRoute
  GuiasOrganizacaoDeTiParaPequenosEscritoriosRoute: typeof GuiasOrganizacaoDeTiParaPequenosEscritoriosRoute
  OperacaoManifestoDeProvasRoute: typeof OperacaoManifestoDeProvasRoute
  OperacaoMensagensProntasRoute: typeof OperacaoMensagensProntasRoute
  OperacaoPainelConversaoRoute: typeof OperacaoPainelConversaoRoute
  OperacaoPainelGoogleBusinessRoute: typeof OperacaoPainelGoogleBusinessRoute
  ServicosSlugRoute: typeof ServicosSlugRoute
  ServicosBackupParaEmpresasRoute: typeof ServicosBackupParaEmpresasRoute
  ServicosConfiguracaoWifiCuritibaRoute: typeof ServicosConfiguracaoWifiCuritibaRoute
  ServicosConsertoDeSomEAudioCuritibaRoute: typeof ServicosConsertoDeSomEAudioCuritibaRoute
  ServicosConsertoDeTelevisaoRoute: typeof ServicosConsertoDeTelevisaoRoute
  ServicosConsertoDeTvRoute: typeof ServicosConsertoDeTvRoute
  ServicosConsertoTvRoute: typeof ServicosConsertoTvRoute
  ServicosManutencaoPreventivaEmpresasRoute: typeof ServicosManutencaoPreventivaEmpresasRoute
  ServicosRedesEWifiRoute: typeof ServicosRedesEWifiRoute
  ServicosReparoSmartTvCuritibaRoute: typeof ServicosReparoSmartTvCuritibaRoute
  ServicosSuporteTecnicoEmpresarialRoute: typeof ServicosSuporteTecnicoEmpresarialRoute
  ServicosTrocaDeTelaTvCuritibaRoute: typeof ServicosTrocaDeTelaTvCuritibaRoute
  SolucoesSlugRoute: typeof SolucoesSlugRoute
  AtendimentoNacionalIndexRoute: typeof AtendimentoNacionalIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  RegioesIndexRoute: typeof RegioesIndexRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
  SolucoesIndexRoute: typeof SolucoesIndexRoute
  AtendimentoNacionalCityBairroRoute: typeof AtendimentoNacionalCityBairroRoute
  BlogCategoriaSlugRoute: typeof BlogCategoriaSlugRoute
  RegioesCityNeighborhoodRoute: typeof RegioesCityNeighborhoodRoute
  ServicoEmCityServiceRoute: typeof ServicoEmCityServiceRoute
  ServicosServicoCuritibaRoute: typeof ServicosServicoCuritibaRoute
  ServicosConfiguracaoWifiCidadeRoute: typeof ServicosConfiguracaoWifiCidadeRoute
  ServicosPcGamerComoFuncionaRoute: typeof ServicosPcGamerComoFuncionaRoute
  ServicosReparoSmartTvCidadeRoute: typeof ServicosReparoSmartTvCidadeRoute
  ServicosTrocaDeTelaTvCidadeRoute: typeof ServicosTrocaDeTelaTvCidadeRoute
  RegioesCityIndexRoute: typeof RegioesCityIndexRoute
  ServicoEmNacionalCityBairroServiceRoute: typeof ServicoEmNacionalCityBairroServiceRoute
  ServicosConfiguracaoWifiCuritibaBairroRoute: typeof ServicosConfiguracaoWifiCuritibaBairroRoute
  ServicosConfiguracaoWifiPinhaisBairroRoute: typeof ServicosConfiguracaoWifiPinhaisBairroRoute
  ServicosConfiguracaoWifiSaoJoseDosPinhaisBairroRoute: typeof ServicosConfiguracaoWifiSaoJoseDosPinhaisBairroRoute
  ServicosReparoSmartTvCuritibaBairroRoute: typeof ServicosReparoSmartTvCuritibaBairroRoute
  ServicosReparoSmartTvPinhaisBairroRoute: typeof ServicosReparoSmartTvPinhaisBairroRoute
  ServicosReparoSmartTvSaoJoseDosPinhaisBairroRoute: typeof ServicosReparoSmartTvSaoJoseDosPinhaisBairroRoute
  ServicosTrocaDeTelaTvPinhaisBairroRoute: typeof ServicosTrocaDeTelaTvPinhaisBairroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abrir-os': {
      id: '/abrir-os'
      path: '/abrir-os'
      fullPath: '/abrir-os'
      preLoaderRoute: typeof AbrirOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-de-atendimento-curitiba': {
      id: '/area-de-atendimento-curitiba'
      path: '/area-de-atendimento-curitiba'
      fullPath: '/area-de-atendimento-curitiba'
      preLoaderRoute: typeof AreaDeAtendimentoCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-atendidas': {
      id: '/areas-atendidas'
      path: '/areas-atendidas'
      fullPath: '/areas-atendidas'
      preLoaderRoute: typeof AreasAtendidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistencia-tecnica': {
      id: '/assistencia-tecnica'
      path: '/assistencia-tecnica'
      fullPath: '/assistencia-tecnica'
      preLoaderRoute: typeof AssistenciaTecnicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistencia-tecnica-curitiba': {
      id: '/assistencia-tecnica-curitiba'
      path: '/assistencia-tecnica-curitiba'
      fullPath: '/assistencia-tecnica-curitiba'
      preLoaderRoute: typeof AssistenciaTecnicaCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistencia-tecnica-empresas-curitiba': {
      id: '/assistencia-tecnica-empresas-curitiba'
      path: '/assistencia-tecnica-empresas-curitiba'
      fullPath: '/assistencia-tecnica-empresas-curitiba'
      preLoaderRoute: typeof AssistenciaTecnicaEmpresasCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento-urgente': {
      id: '/atendimento-urgente'
      path: '/atendimento-urgente'
      fullPath: '/atendimento-urgente'
      preLoaderRoute: typeof AtendimentoUrgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliar': {
      id: '/avaliar'
      path: '/avaliar'
      fullPath: '/avaliar'
      preLoaderRoute: typeof AvaliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist-publicacao': {
      id: '/checklist-publicacao'
      path: '/checklist-publicacao'
      fullPath: '/checklist-publicacao'
      preLoaderRoute: typeof ChecklistPublicacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists-de-reparo': {
      id: '/checklists-de-reparo'
      path: '/checklists-de-reparo'
      fullPath: '/checklists-de-reparo'
      preLoaderRoute: typeof ChecklistsDeReparoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-avaliar': {
      id: '/como-avaliar'
      path: '/como-avaliar'
      fullPath: '/como-avaliar'
      preLoaderRoute: typeof ComoAvaliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-escolher-tecnico-preco-prazo': {
      id: '/como-escolher-tecnico-preco-prazo'
      path: '/como-escolher-tecnico-preco-prazo'
      fullPath: '/como-escolher-tecnico-preco-prazo'
      preLoaderRoute: typeof ComoEscolherTecnicoPrecoPrazoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conserto-de-notebook-curitiba': {
      id: '/conserto-de-notebook-curitiba'
      path: '/conserto-de-notebook-curitiba'
      fullPath: '/conserto-de-notebook-curitiba'
      preLoaderRoute: typeof ConsertoDeNotebookCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultar-os': {
      id: '/consultar-os'
      path: '/consultar-os'
      fullPath: '/consultar-os'
      preLoaderRoute: typeof ConsultarOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos-de-imagens': {
      id: '/creditos-de-imagens'
      path: '/creditos-de-imagens'
      fullPath: '/creditos-de-imagens'
      preLoaderRoute: typeof CreditosDeImagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados-da-empresa': {
      id: '/dados-da-empresa'
      path: '/dados-da-empresa'
      fullPath: '/dados-da-empresa'
      preLoaderRoute: typeof DadosDaEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa-de-ti-curitiba': {
      id: '/empresa-de-ti-curitiba'
      path: '/empresa-de-ti-curitiba'
      fullPath: '/empresa-de-ti-curitiba'
      preLoaderRoute: typeof EmpresaDeTiCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusao-de-dados': {
      id: '/exclusao-de-dados'
      path: '/exclusao-de-dados'
      fullPath: '/exclusao-de-dados'
      preLoaderRoute: typeof ExclusaoDeDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formatacao-de-computador-curitiba': {
      id: '/formatacao-de-computador-curitiba'
      path: '/formatacao-de-computador-curitiba'
      fullPath: '/formatacao-de-computador-curitiba'
      preLoaderRoute: typeof FormatacaoDeComputadorCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantia-e-cobertura': {
      id: '/garantia-e-cobertura'
      path: '/garantia-e-cobertura'
      fullPath: '/garantia-e-cobertura'
      preLoaderRoute: typeof GarantiaECoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor-responsavel': {
      id: '/gestor-responsavel'
      path: '/gestor-responsavel'
      fullPath: '/gestor-responsavel'
      preLoaderRoute: typeof GestorResponsavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-tecnico-informatica': {
      id: '/guia-tecnico-informatica'
      path: '/guia-tecnico-informatica'
      fullPath: '/guia-tecnico-informatica'
      preLoaderRoute: typeof GuiaTecnicoInformaticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordem-de-servico': {
      id: '/ordem-de-servico'
      path: '/ordem-de-servico'
      fullPath: '/ordem-de-servico'
      preLoaderRoute: typeof OrdemDeServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinadores': {
      id: '/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/patrocinadores'
      preLoaderRoute: typeof PatrocinadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-anuncios': {
      id: '/politica-de-anuncios'
      path: '/politica-de-anuncios'
      fullPath: '/politica-de-anuncios'
      preLoaderRoute: typeof PoliticaDeAnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-pecas-do-cliente': {
      id: '/politica-de-pecas-do-cliente'
      path: '/politica-de-pecas-do-cliente'
      fullPath: '/politica-de-pecas-do-cliente'
      preLoaderRoute: typeof PoliticaDePecasDoClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos-e-politicas': {
      id: '/precos-e-politicas'
      path: '/precos-e-politicas'
      fullPath: '/precos-e-politicas'
      preLoaderRoute: typeof PrecosEPoliticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo-de-atendimento': {
      id: '/processo-de-atendimento'
      path: '/processo-de-atendimento'
      fullPath: '/processo-de-atendimento'
      preLoaderRoute: typeof ProcessoDeAtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicidade': {
      id: '/publicidade'
      path: '/publicidade'
      fullPath: '/publicidade'
      preLoaderRoute: typeof PublicidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remocao-de-virus-curitiba': {
      id: '/remocao-de-virus-curitiba'
      path: '/remocao-de-virus-curitiba'
      fullPath: '/remocao-de-virus-curitiba'
      preLoaderRoute: typeof RemocaoDeVirusCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca-dos-dados': {
      id: '/seguranca-dos-dados'
      path: '/seguranca-dos-dados'
      fullPath: '/seguranca-dos-dados'
      preLoaderRoute: typeof SegurancaDosDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seja-patrocinador': {
      id: '/seja-patrocinador'
      path: '/seja-patrocinador'
      fullPath: '/seja-patrocinador'
      preLoaderRoute: typeof SejaPatrocinadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status-anuncios': {
      id: '/status-anuncios'
      path: '/status-anuncios'
      fullPath: '/status-anuncios'
      preLoaderRoute: typeof StatusAnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status-da-ordem-de-servico': {
      id: '/status-da-ordem-de-servico'
      path: '/status-da-ordem-de-servico'
      fullPath: '/status-da-ordem-de-servico'
      preLoaderRoute: typeof StatusDaOrdemDeServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status-os': {
      id: '/status-os'
      path: '/status-os'
      fullPath: '/status-os'
      preLoaderRoute: typeof StatusOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte-tecnico-remoto': {
      id: '/suporte-tecnico-remoto'
      path: '/suporte-tecnico-remoto'
      fullPath: '/suporte-tecnico-remoto'
      preLoaderRoute: typeof SuporteTecnicoRemotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-orcamento': {
      id: '/termos-orcamento'
      path: '/termos-orcamento'
      fullPath: '/termos-orcamento'
      preLoaderRoute: typeof TermosOrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-orcamento-pre-aprovado': {
      id: '/termos-orcamento-pre-aprovado'
      path: '/termos-orcamento-pre-aprovado'
      fullPath: '/termos-orcamento-pre-aprovado'
      preLoaderRoute: typeof TermosOrcamentoPreAprovadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-uso': {
      id: '/termos-uso'
      path: '/termos-uso'
      fullPath: '/termos-uso'
      preLoaderRoute: typeof TermosUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triagem-preview': {
      id: '/triagem-preview'
      path: '/triagem-preview'
      fullPath: '/triagem-preview'
      preLoaderRoute: typeof TriagemPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade-memoria-ram-curitiba': {
      id: '/upgrade-memoria-ram-curitiba'
      path: '/upgrade-memoria-ram-curitiba'
      fullPath: '/upgrade-memoria-ram-curitiba'
      preLoaderRoute: typeof UpgradeMemoriaRamCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade-ssd-curitiba': {
      id: '/upgrade-ssd-curitiba'
      path: '/upgrade-ssd-curitiba'
      fullPath: '/upgrade-ssd-curitiba'
      preLoaderRoute: typeof UpgradeSsdCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento-nacional/': {
      id: '/atendimento-nacional/'
      path: '/atendimento-nacional'
      fullPath: '/atendimento-nacional/'
      preLoaderRoute: typeof AtendimentoNacionalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento-nacional/$slug': {
      id: '/atendimento-nacional/$slug'
      path: '/atendimento-nacional/$slug'
      fullPath: '/atendimento-nacional/$slug'
      preLoaderRoute: typeof AtendimentoNacionalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/como-escolher-uma-workstation': {
      id: '/guias/como-escolher-uma-workstation'
      path: '/guias/como-escolher-uma-workstation'
      fullPath: '/guias/como-escolher-uma-workstation'
      preLoaderRoute: typeof GuiasComoEscolherUmaWorkstationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/organizacao-de-ti-para-pequenos-escritorios': {
      id: '/guias/organizacao-de-ti-para-pequenos-escritorios'
      path: '/guias/organizacao-de-ti-para-pequenos-escritorios'
      fullPath: '/guias/organizacao-de-ti-para-pequenos-escritorios'
      preLoaderRoute: typeof GuiasOrganizacaoDeTiParaPequenosEscritoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao/manifesto-de-provas': {
      id: '/operacao/manifesto-de-provas'
      path: '/operacao/manifesto-de-provas'
      fullPath: '/operacao/manifesto-de-provas'
      preLoaderRoute: typeof OperacaoManifestoDeProvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao/mensagens-prontas': {
      id: '/operacao/mensagens-prontas'
      path: '/operacao/mensagens-prontas'
      fullPath: '/operacao/mensagens-prontas'
      preLoaderRoute: typeof OperacaoMensagensProntasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao/painel-conversao': {
      id: '/operacao/painel-conversao'
      path: '/operacao/painel-conversao'
      fullPath: '/operacao/painel-conversao'
      preLoaderRoute: typeof OperacaoPainelConversaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao/painel-google-business': {
      id: '/operacao/painel-google-business'
      path: '/operacao/painel-google-business'
      fullPath: '/operacao/painel-google-business'
      preLoaderRoute: typeof OperacaoPainelGoogleBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regioes/': {
      id: '/regioes/'
      path: '/regioes'
      fullPath: '/regioes/'
      preLoaderRoute: typeof RegioesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/servicos/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/backup-para-empresas': {
      id: '/servicos/backup-para-empresas'
      path: '/servicos/backup-para-empresas'
      fullPath: '/servicos/backup-para-empresas'
      preLoaderRoute: typeof ServicosBackupParaEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/configuracao-wifi-curitiba': {
      id: '/servicos/configuracao-wifi-curitiba'
      path: '/servicos/configuracao-wifi-curitiba'
      fullPath: '/servicos/configuracao-wifi-curitiba'
      preLoaderRoute: typeof ServicosConfiguracaoWifiCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/conserto-de-som-e-audio-curitiba': {
      id: '/servicos/conserto-de-som-e-audio-curitiba'
      path: '/servicos/conserto-de-som-e-audio-curitiba'
      fullPath: '/servicos/conserto-de-som-e-audio-curitiba'
      preLoaderRoute: typeof ServicosConsertoDeSomEAudioCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/conserto-de-televisao': {
      id: '/servicos/conserto-de-televisao'
      path: '/servicos/conserto-de-televisao'
      fullPath: '/servicos/conserto-de-televisao'
      preLoaderRoute: typeof ServicosConsertoDeTelevisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/conserto-de-tv': {
      id: '/servicos/conserto-de-tv'
      path: '/servicos/conserto-de-tv'
      fullPath: '/servicos/conserto-de-tv'
      preLoaderRoute: typeof ServicosConsertoDeTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/conserto-tv': {
      id: '/servicos/conserto-tv'
      path: '/servicos/conserto-tv'
      fullPath: '/servicos/conserto-tv'
      preLoaderRoute: typeof ServicosConsertoTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/manutencao-preventiva-empresas': {
      id: '/servicos/manutencao-preventiva-empresas'
      path: '/servicos/manutencao-preventiva-empresas'
      fullPath: '/servicos/manutencao-preventiva-empresas'
      preLoaderRoute: typeof ServicosManutencaoPreventivaEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/redes-e-wifi': {
      id: '/servicos/redes-e-wifi'
      path: '/servicos/redes-e-wifi'
      fullPath: '/servicos/redes-e-wifi'
      preLoaderRoute: typeof ServicosRedesEWifiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/reparo-smart-tv-curitiba': {
      id: '/servicos/reparo-smart-tv-curitiba'
      path: '/servicos/reparo-smart-tv-curitiba'
      fullPath: '/servicos/reparo-smart-tv-curitiba'
      preLoaderRoute: typeof ServicosReparoSmartTvCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/suporte-tecnico-empresarial': {
      id: '/servicos/suporte-tecnico-empresarial'
      path: '/servicos/suporte-tecnico-empresarial'
      fullPath: '/servicos/suporte-tecnico-empresarial'
      preLoaderRoute: typeof ServicosSuporteTecnicoEmpresarialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/troca-de-tela-tv-curitiba': {
      id: '/servicos/troca-de-tela-tv-curitiba'
      path: '/servicos/troca-de-tela-tv-curitiba'
      fullPath: '/servicos/troca-de-tela-tv-curitiba'
      preLoaderRoute: typeof ServicosTrocaDeTelaTvCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/': {
      id: '/solucoes/'
      path: '/solucoes'
      fullPath: '/solucoes/'
      preLoaderRoute: typeof SolucoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/$slug': {
      id: '/solucoes/$slug'
      path: '/solucoes/$slug'
      fullPath: '/solucoes/$slug'
      preLoaderRoute: typeof SolucoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento-nacional/$city/$bairro': {
      id: '/atendimento-nacional/$city/$bairro'
      path: '/atendimento-nacional/$city/$bairro'
      fullPath: '/atendimento-nacional/$city/$bairro'
      preLoaderRoute: typeof AtendimentoNacionalCityBairroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/categoria/$slug': {
      id: '/blog/categoria/$slug'
      path: '/blog/categoria/$slug'
      fullPath: '/blog/categoria/$slug'
      preLoaderRoute: typeof BlogCategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regioes/$city/': {
      id: '/regioes/$city/'
      path: '/regioes/$city'
      fullPath: '/regioes/$city/'
      preLoaderRoute: typeof RegioesCityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regioes/$city/$neighborhood': {
      id: '/regioes/$city/$neighborhood'
      path: '/regioes/$city/$neighborhood'
      fullPath: '/regioes/$city/$neighborhood'
      preLoaderRoute: typeof RegioesCityNeighborhoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servico-em/$city/$service': {
      id: '/servico-em/$city/$service'
      path: '/servico-em/$city/$service'
      fullPath: '/servico-em/$city/$service'
      preLoaderRoute: typeof ServicoEmCityServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$servico/curitiba': {
      id: '/servicos/$servico/curitiba'
      path: '/servicos/$servico/curitiba'
      fullPath: '/servicos/$servico/curitiba'
      preLoaderRoute: typeof ServicosServicoCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/configuracao-wifi/$cidade': {
      id: '/servicos/configuracao-wifi/$cidade'
      path: '/servicos/configuracao-wifi/$cidade'
      fullPath: '/servicos/configuracao-wifi/$cidade'
      preLoaderRoute: typeof ServicosConfiguracaoWifiCidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/pc-gamer/como-funciona': {
      id: '/servicos/pc-gamer/como-funciona'
      path: '/servicos/pc-gamer/como-funciona'
      fullPath: '/servicos/pc-gamer/como-funciona'
      preLoaderRoute: typeof ServicosPcGamerComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/reparo-smart-tv/$cidade': {
      id: '/servicos/reparo-smart-tv/$cidade'
      path: '/servicos/reparo-smart-tv/$cidade'
      fullPath: '/servicos/reparo-smart-tv/$cidade'
      preLoaderRoute: typeof ServicosReparoSmartTvCidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/troca-de-tela-tv/$cidade': {
      id: '/servicos/troca-de-tela-tv/$cidade'
      path: '/servicos/troca-de-tela-tv/$cidade'
      fullPath: '/servicos/troca-de-tela-tv/$cidade'
      preLoaderRoute: typeof ServicosTrocaDeTelaTvCidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servico-em-nacional/$city/$bairro/$service': {
      id: '/servico-em-nacional/$city/$bairro/$service'
      path: '/servico-em-nacional/$city/$bairro/$service'
      fullPath: '/servico-em-nacional/$city/$bairro/$service'
      preLoaderRoute: typeof ServicoEmNacionalCityBairroServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/configuracao-wifi/curitiba/$bairro': {
      id: '/servicos/configuracao-wifi/curitiba/$bairro'
      path: '/servicos/configuracao-wifi/curitiba/$bairro'
      fullPath: '/servicos/configuracao-wifi/curitiba/$bairro'
      preLoaderRoute: typeof ServicosConfiguracaoWifiCuritibaBairroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/configuracao-wifi/pinhais/$bairro': {
      id: '/servicos/configuracao-wifi/pinhais/$bairro'
      path: '/servicos/configuracao-wifi/pinhais/$bairro'
      fullPath: '/servicos/configuracao-wifi/pinhais/$bairro'
      preLoaderRoute: typeof ServicosConfiguracaoWifiPinhaisBairroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/configuracao-wifi/sao-jose-dos-pinhais/$bairro': {
      id: '/servicos/configuracao-wifi/sao-jose-dos-pinhais/$bairro'
      path: '/servicos/configuracao-wifi/sao-jose-dos-pinhais/$bairro'
      fullPath: '/servicos/configuracao-wifi/sao-jose-dos-pinhais/$bairro'
      preLoaderRoute: typeof ServicosConfiguracaoWifiSaoJoseDosPinhaisBairroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/reparo-smart-tv/curitiba/$bairro': {
      id: '/servicos/reparo-smart-tv/curitiba/$bairro'
      path: '/servicos/reparo-smart-tv/curitiba/$bairro'
      fullPath: '/servicos/reparo-smart-tv/curitiba/$bairro'
      preLoaderRoute: typeof ServicosReparoSmartTvCuritibaBairroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/reparo-smart-tv/pinhais/$bairro': {
      id: '/servicos/reparo-smart-tv/pinhais/$bairro'
      path: '/servicos/reparo-smart-tv/pinhais/$bairro'
      fullPath: '/servicos/reparo-smart-tv/pinhais/$bairro'
      preLoaderRoute: typeof ServicosReparoSmartTvPinhaisBairroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/reparo-smart-tv/sao-jose-dos-pinhais/$bairro': {
      id: '/servicos/reparo-smart-tv/sao-jose-dos-pinhais/$bairro'
      path: '/servicos/reparo-smart-tv/sao-jose-dos-pinhais/$bairro'
      fullPath: '/servicos/reparo-smart-tv/sao-jose-dos-pinhais/$bairro'
      preLoaderRoute: typeof ServicosReparoSmartTvSaoJoseDosPinhaisBairroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/troca-de-tela-tv/pinhais/$bairro': {
      id: '/servicos/troca-de-tela-tv/pinhais/$bairro'
      path: '/servicos/troca-de-tela-tv/pinhais/$bairro'
      fullPath: '/servicos/troca-de-tela-tv/pinhais/$bairro'
      preLoaderRoute: typeof ServicosTrocaDeTelaTvPinhaisBairroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbrirOsRoute: AbrirOsRoute,
  AdminRoute: AdminRoute,
  AnuncieRoute: AnuncieRoute,
  AreaDeAtendimentoCuritibaRoute: AreaDeAtendimentoCuritibaRoute,
  AreasAtendidasRoute: AreasAtendidasRoute,
  AssistenciaTecnicaRoute: AssistenciaTecnicaRoute,
  AssistenciaTecnicaCuritibaRoute: AssistenciaTecnicaCuritibaRoute,
  AssistenciaTecnicaEmpresasCuritibaRoute:
    AssistenciaTecnicaEmpresasCuritibaRoute,
  AtendimentoUrgenteRoute: AtendimentoUrgenteRoute,
  AuthRoute: AuthRoute,
  AvaliacoesRoute: AvaliacoesRoute,
  AvaliarRoute: AvaliarRoute,
  BuscaRoute: BuscaRoute,
  ChecklistPublicacaoRoute: ChecklistPublicacaoRoute,
  ChecklistsDeReparoRoute: ChecklistsDeReparoRoute,
  ComoAvaliarRoute: ComoAvaliarRoute,
  ComoEscolherTecnicoPrecoPrazoRoute: ComoEscolherTecnicoPrecoPrazoRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ConsertoDeNotebookCuritibaRoute: ConsertoDeNotebookCuritibaRoute,
  ConsultarOsRoute: ConsultarOsRoute,
  ContatoRoute: ContatoRoute,
  CreditosDeImagensRoute: CreditosDeImagensRoute,
  DadosDaEmpresaRoute: DadosDaEmpresaRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  EmpresaDeTiCuritibaRoute: EmpresaDeTiCuritibaRoute,
  ExclusaoDeDadosRoute: ExclusaoDeDadosRoute,
  FaqRoute: FaqRoute,
  FormatacaoDeComputadorCuritibaRoute: FormatacaoDeComputadorCuritibaRoute,
  GarantiaECoberturaRoute: GarantiaECoberturaRoute,
  GestorResponsavelRoute: GestorResponsavelRoute,
  GuiaTecnicoInformaticaRoute: GuiaTecnicoInformaticaRoute,
  ObrigadoRoute: ObrigadoRoute,
  OrdemDeServicoRoute: OrdemDeServicoRoute,
  PatrocinadoresRoute: PatrocinadoresRoute,
  PoliticaDeAnunciosRoute: PoliticaDeAnunciosRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePecasDoClienteRoute: PoliticaDePecasDoClienteRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PoliticaPrivacidadeRoute: PoliticaPrivacidadeRoute,
  PrecosRoute: PrecosRoute,
  PrecosEPoliticasRoute: PrecosEPoliticasRoute,
  ProcessoDeAtendimentoRoute: ProcessoDeAtendimentoRoute,
  PublicidadeRoute: PublicidadeRoute,
  RemocaoDeVirusCuritibaRoute: RemocaoDeVirusCuritibaRoute,
  SegurancaDosDadosRoute: SegurancaDosDadosRoute,
  SejaPatrocinadorRoute: SejaPatrocinadorRoute,
  SobreRoute: SobreRoute,
  StatusAnunciosRoute: StatusAnunciosRoute,
  StatusDaOrdemDeServicoRoute: StatusDaOrdemDeServicoRoute,
  StatusOsRoute: StatusOsRoute,
  SuporteTecnicoRemotoRoute: SuporteTecnicoRemotoRoute,
  TermosOrcamentoRoute: TermosOrcamentoRoute,
  TermosOrcamentoPreAprovadoRoute: TermosOrcamentoPreAprovadoRoute,
  TermosUsoRoute: TermosUsoRoute,
  TriagemPreviewRoute: TriagemPreviewRoute,
  UpgradeMemoriaRamCuritibaRoute: UpgradeMemoriaRamCuritibaRoute,
  UpgradeSsdCuritibaRoute: UpgradeSsdCuritibaRoute,
  AtendimentoNacionalSlugRoute: AtendimentoNacionalSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  GuiasComoEscolherUmaWorkstationRoute: GuiasComoEscolherUmaWorkstationRoute,
  GuiasOrganizacaoDeTiParaPequenosEscritoriosRoute:
    GuiasOrganizacaoDeTiParaPequenosEscritoriosRoute,
  OperacaoManifestoDeProvasRoute: OperacaoManifestoDeProvasRoute,
  OperacaoMensagensProntasRoute: OperacaoMensagensProntasRoute,
  OperacaoPainelConversaoRoute: OperacaoPainelConversaoRoute,
  OperacaoPainelGoogleBusinessRoute: OperacaoPainelGoogleBusinessRoute,
  ServicosSlugRoute: ServicosSlugRoute,
  ServicosBackupParaEmpresasRoute: ServicosBackupParaEmpresasRoute,
  ServicosConfiguracaoWifiCuritibaRoute: ServicosConfiguracaoWifiCuritibaRoute,
  ServicosConsertoDeSomEAudioCuritibaRoute:
    ServicosConsertoDeSomEAudioCuritibaRoute,
  ServicosConsertoDeTelevisaoRoute: ServicosConsertoDeTelevisaoRoute,
  ServicosConsertoDeTvRoute: ServicosConsertoDeTvRoute,
  ServicosConsertoTvRoute: ServicosConsertoTvRoute,
  ServicosManutencaoPreventivaEmpresasRoute:
    ServicosManutencaoPreventivaEmpresasRoute,
  ServicosRedesEWifiRoute: ServicosRedesEWifiRoute,
  ServicosReparoSmartTvCuritibaRoute: ServicosReparoSmartTvCuritibaRoute,
  ServicosSuporteTecnicoEmpresarialRoute:
    ServicosSuporteTecnicoEmpresarialRoute,
  ServicosTrocaDeTelaTvCuritibaRoute: ServicosTrocaDeTelaTvCuritibaRoute,
  SolucoesSlugRoute: SolucoesSlugRoute,
  AtendimentoNacionalIndexRoute: AtendimentoNacionalIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  RegioesIndexRoute: RegioesIndexRoute,
  ServicosIndexRoute: ServicosIndexRoute,
  SolucoesIndexRoute: SolucoesIndexRoute,
  AtendimentoNacionalCityBairroRoute: AtendimentoNacionalCityBairroRoute,
  BlogCategoriaSlugRoute: BlogCategoriaSlugRoute,
  RegioesCityNeighborhoodRoute: RegioesCityNeighborhoodRoute,
  ServicoEmCityServiceRoute: ServicoEmCityServiceRoute,
  ServicosServicoCuritibaRoute: ServicosServicoCuritibaRoute,
  ServicosConfiguracaoWifiCidadeRoute: ServicosConfiguracaoWifiCidadeRoute,
  ServicosPcGamerComoFuncionaRoute: ServicosPcGamerComoFuncionaRoute,
  ServicosReparoSmartTvCidadeRoute: ServicosReparoSmartTvCidadeRoute,
  ServicosTrocaDeTelaTvCidadeRoute: ServicosTrocaDeTelaTvCidadeRoute,
  RegioesCityIndexRoute: RegioesCityIndexRoute,
  ServicoEmNacionalCityBairroServiceRoute:
    ServicoEmNacionalCityBairroServiceRoute,
  ServicosConfiguracaoWifiCuritibaBairroRoute:
    ServicosConfiguracaoWifiCuritibaBairroRoute,
  ServicosConfiguracaoWifiPinhaisBairroRoute:
    ServicosConfiguracaoWifiPinhaisBairroRoute,
  ServicosConfiguracaoWifiSaoJoseDosPinhaisBairroRoute:
    ServicosConfiguracaoWifiSaoJoseDosPinhaisBairroRoute,
  ServicosReparoSmartTvCuritibaBairroRoute:
    ServicosReparoSmartTvCuritibaBairroRoute,
  ServicosReparoSmartTvPinhaisBairroRoute:
    ServicosReparoSmartTvPinhaisBairroRoute,
  ServicosReparoSmartTvSaoJoseDosPinhaisBairroRoute:
    ServicosReparoSmartTvSaoJoseDosPinhaisBairroRoute,
  ServicosTrocaDeTelaTvPinhaisBairroRoute:
    ServicosTrocaDeTelaTvPinhaisBairroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
